In [1]:
import numpy as np

In [2]:
a = [i for i in range(10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array([1,2,3,4,5])

In [7]:
b

array([1, 2, 3, 4, 5])

In [8]:
b = np.array([i for i in range(15)])

In [9]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
c = (0, 1, 2, 3, 4, 5)

In [12]:
b = np.array(c)

In [13]:
b

array([0, 1, 2, 3, 4, 5])

In [14]:
type(b)

numpy.ndarray

In [15]:
b = np.array(a, dtype = float)

In [16]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
b = np.array(a, dtype = str)

In [18]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U1')

In [19]:
b = np.array(a, dtype = int)

In [20]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b.dtype

dtype('int64')

In [22]:
b[2]

2

In [23]:
b[3]

3

In [24]:
b[0]

0

In [25]:
b.ndim

1

In [26]:
b.shape

(10,)

In [29]:
#### 2d array

In [30]:
b = np.array([[1,2,3], [9,6,5], [2,5,6]])

In [31]:
b

array([[1, 2, 3],
       [9, 6, 5],
       [2, 5, 6]])

In [32]:
b.shape

(3, 3)

In [33]:
b.size

9

In [36]:
b[0][2]

3

In [38]:
b[0,2]

3

In [40]:
b[1:2, 0:2]

array([[9, 6]])

In [41]:
c = b[1:2, :2]

In [42]:
c

array([[9, 6]])

In [43]:
c[0,1] = 555

In [44]:
c

array([[  9, 555]])

In [45]:
b

array([[  1,   2,   3],
       [  9, 555,   5],
       [  2,   5,   6]])