****Задание на повторение материала**

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [1]:
import numpy as np

In [2]:
a = np.array([i for i in range(12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
b1 = np.reshape(a, (2, 6))
b2 = np.reshape(a, (6, 2))
b3 = np.reshape(a, (3, 4))
b4 = np.reshape(a, (4, 3))
b5 = np.reshape(a, (12, 1))
print('b1:', b1, '\nb2:', b2, '\nb3:', b3, '\nb4:', b4, '\nb5:', b5)

b1: [[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 
b2: [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 
b3: [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 
b4: [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 
b5: [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
c1 = np.reshape(a, (12, -1))
c2 = np.reshape(a, (3, -1))
c3 = np.reshape(a, (4, -1))
c4 = np.reshape(a, (-1, 6))
c5 = np.reshape(a, (-1, 2))
c5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

4.  Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? - Нет, появление строк уже предполагает 2 измерения.

In [13]:
b5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [12]:
b5.ndim

2

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [15]:
n = np.random.randn(3, 4)

array([[ 0.59848484,  0.47609134,  0.21343584, -1.78067097],
       [ 0.09840035,  1.75053628,  0.78825014, -1.67876601],
       [-0.10999461, -1.36924308,  0.56945563,  0.22017979]])

In [17]:
n_flat = n.flatten()
n_flat

(array([ 0.59848484,  0.47609134,  0.21343584, -1.78067097,  0.09840035,
         1.75053628,  0.78825014, -1.67876601, -0.10999461, -1.36924308,
         0.56945563,  0.22017979]),
 12)

In [19]:
n.size == n_flat.size

True

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [26]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?  
- разница в размерности: массив а - одномерный, массив b - двумерный 

In [32]:
b = a.reshape(10,1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

In [33]:
a.ndim, b.ndim

((10,), (10, 1), 1, 2)

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [41]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
v.size, v

(10,
 array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]))

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?  
- не получится, так как ее определитель равен нулю, обратной матрицы не существует

In [58]:
a = np.arange(12)
A = a.reshape(4, 3)
# a.reshape(4,3)
a, A

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [59]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [63]:
B = np.dot(A, At)
B.size, B

(16,
 array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]))

In [64]:
np.linalg.det(B)

0.0

10.  Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [50]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [70]:
c = np.random.randint(0, 16, 16)
c

array([11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [74]:
C = c.reshape(4, 4)
C

array([[11,  9,  5, 12],
       [11,  8,  0, 10],
       [10, 14,  9, 15],
       [11, 11, 15, 14]])

In [76]:
D = C * 10 + B
D

array([[115, 104,  73, 152],
       [124, 130,  86, 222],
       [123, 226, 239, 362],
       [142, 232, 362, 442]])

In [77]:
np.linalg.det(D)

62650800.0

In [78]:
np.linalg.matrix_rank(A)

2

In [80]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.01886552, -0.00325327, -0.01147599,  0.00454519],
       [ 0.01683203, -0.02439777,  0.02559361, -0.01449559],
       [ 0.01273886, -0.01565599, -0.00270994,  0.00570208],
       [-0.02532897,  0.02667356, -0.00752744,  0.00374073]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [87]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.]])

In [88]:
E = np.where(D_inv, B, C)
E

array([[  5,   9,   5,  32],
       [ 14,   8,  86,  10],
       [ 23,  14,   9, 212],
       [ 11, 122,  15, 302]])