**Задание на повторение материала

1 Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [1]:
import numpy as np

In [3]:
a = np.array([i for i in range(12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2 Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [27]:
b1 = np.reshape(a, (2, 6))
b2 = np.reshape(a, (6, 2))
b3 = np.reshape(a, (3, 4))
b4 = np.reshape(a, (4, 3))
b5 = np.reshape(a, (12, 1))
print('b1:', b1, '\nb2:', b2, '\nb3:', b3, '\nb4:', b4, '\nb5:', b5)

b1: [[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 
b2: [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 
b3: [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 
b4: [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 
b5: [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


3 Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [34]:
c1 = np.reshape(a, (12, -1))
c2 = np.reshape(a, (3, -1))
c3 = np.reshape(a, (4, -1))
c4 = np.reshape(a, (-1, 6))
c5 = np.reshape(a, (-1, 2))
c5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

4 Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [35]:
np.shape(a)

(12,)

In [36]:
np.shape(b5)

(12, 1)

In [38]:
at = a.transpose()
np.shape(at)

(12,)

In [39]:
b5t = b5.transpose()
np.shape(b5t)

(1, 12)