**Задание 1**  
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [3]:
import numpy as np

In [4]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = a.mean(axis = 0)

In [6]:
mean_a

array([2. , 8.4])

**Задание 2**  
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [7]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание 3**  
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [8]:
y1 = a_centered[:, :1].T
y1 = y1.flatten()
y1

array([-1.,  0.,  1.,  1., -1.])

In [9]:
y2 = a_centered[:,1:].T
y2 = y2.flatten()
y2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [10]:
a_centered_sp = y1 @ y2
a_centered_sp

8.0

In [11]:
N = y1.shape[0]

In [12]:
a_centered_sp / (N - 1)

2.0

**Задание 4****  
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [13]:
m = a.T

In [14]:
cov_a = np.cov(m)
cov_a[0, 1]

2.0

**Задание 5****  
Создайте одномерный массив z случайных нормально распределенных целых чисел от -50 до 50 включительно размерности 8. Найдите индексы положительных объектов.


In [15]:
from scipy.stats import truncnorm
z = truncnorm(a=-50/30, b=50/30, scale=30).rvs(size=8).astype(int)
z

array([-20,  27,   3, -11, -35, -13,   2,   7])

In [16]:
np.where(z > 0)

(array([1, 2, 6, 7]),)

In [17]:
np.random.seed(24)
z = np.random.randint(-50, 50, 8)
z

array([-16, -47,  14,  37, -33, -33, -49,  29])

In [18]:
np.where(z > 0)

(array([2, 3, 7]),)

**Задание 6****  
Создайте двумерный массив X случайных равномерно распределенных целых чисел от 0 до 255 включительно размерности 10 на 5. (Здесь снова считаем, что каждый столбец - это признак, а строка - наблюдение.)
Найдите среднее значение и стандартное отклонение по каждому признаку.
Вычислите массив X_standard, отняв от каждого признака среднее и поделив на стандартное отклонение.
Убедитесь, что теперь среднее в каждом признаке стало равное нулю, а стандартное отклонение равно единице.
Это называется стандартизация данных - важный процесс подготовки данных. Более подробно можно почитать здесь (https://wiki.loginom.ru/articles/data-standartization.html)

In [19]:
np.random.seed(24)
X = np.random.randint(0, 255, (10, 5))
X

array([[162, 131, 192,  87, 145],
       [145, 129, 100, 123, 207],
       [  4, 239, 227,  82, 139],
       [123, 227, 115, 143, 231],
       [ 73,  18, 119, 135, 153],
       [163, 237, 223,  28, 128],
       [254,  12, 223,  33, 129],
       [ 60,  55,  70,  97, 209],
       [134,  46,  65, 118, 175],
       [217,  74, 163, 192, 250]])

In [20]:
mean_X = X.mean(axis=0)
mean_X

array([133.5, 116.8, 149.7, 103.8, 176.6])

In [21]:
std_X = X.std(axis=0)
std_X

array([70.17870047, 85.60584092, 60.68780767, 47.35145193, 42.33249343])

In [22]:
X_standard = (X - mean_X) / std_X
X_standard

array([[ 0.40610612,  0.16587653,  0.69700985, -0.35479377, -0.7464715 ],
       [ 0.16386738,  0.14251364, -0.81894538,  0.40547859,  0.71812448],
       [-1.84528923,  1.42747269,  1.27373196, -0.46038715, -0.8882066 ],
       [-0.14961805,  1.28729534, -0.57177877,  0.82785212,  1.28506487],
       [-0.86208493, -1.15412686, -0.50586767,  0.65890271, -0.55749138],
       [ 0.42035546,  1.4041098 ,  1.20782086, -1.60079569, -1.14805427],
       [ 1.71704519, -1.22421553,  1.20782086, -1.4952023 , -1.12443176],
       [-1.04732632, -0.72191336, -1.31327861, -0.143607  ,  0.76536952],
       [ 0.00712467, -0.82704637, -1.39566749,  0.29988521, -0.03779603],
       [ 1.1898197 , -0.49996588,  0.2191544 ,  1.86266728,  1.73389267]])

In [23]:
X_standard.mean(axis=0)

array([0.00000000e+00, 5.55111512e-17, 1.55431223e-16, 2.22044605e-17,
       1.55431223e-16])

In [24]:
X_standard.std(axis=0)

array([1., 1., 1., 1., 1.])

**Задание 7****  
Создайте два одномерных массива размерности 512 с любыми значениями. Будем считать, что каждый массив - это наблюдение с 512 признаками. 
Найдите разницу между двумя массивами. Далее возведите разницу в квадрат, просуммируйте все элементы нового массива и возьмите корень квадратный.
Это получилась L2-норма (Евклидова метрика) — функция расстояния, благодаря которой можно считать насколько далеки точки друг от друга, насколько они похожи друг на друга. Более подробно здесь (https://wiki.loginom.ru/articles/euclid-distance.html)
Посчитайте L2 норму для этих двух массивов с помощью numpy.linalg.

In [25]:
np.random.seed(512)
a = 5 * np.random.randn(512)
b = (35 * np.random.sample(512)).astype(int) 
L2_norm = np.sqrt(np.power(a - b, 2).sum())
L2_norm

466.19567944556644

**Задание 8****  
Используйте ранее созданный массив X.
Найдите минимальное значение и максимальное по каждому признаку.
Вычислите массив X_norm, отняв от каждого признака минимальное и поделив на разницу максимального и минимального.
Убедитесь, что теперь минимальное значение стало равно 0, а максимальное - 1.
Это называется нормализация данных - еще один из важных процессов подготовки данных. Более подробно здесь (https://wiki.loginom.ru/articles/data-normalization.html)

In [26]:
X

array([[162, 131, 192,  87, 145],
       [145, 129, 100, 123, 207],
       [  4, 239, 227,  82, 139],
       [123, 227, 115, 143, 231],
       [ 73,  18, 119, 135, 153],
       [163, 237, 223,  28, 128],
       [254,  12, 223,  33, 129],
       [ 60,  55,  70,  97, 209],
       [134,  46,  65, 118, 175],
       [217,  74, 163, 192, 250]])

In [27]:
max_X = X.max(axis=0)
max_X

array([254, 239, 227, 192, 250])

In [28]:
min_X = X.min(axis=0)
min_X

array([  4,  12,  65,  28, 128])

In [29]:
dif = max_X - min_X
dif

array([250, 227, 162, 164, 122])

In [30]:
X_norm = (X - min_X) / dif
X_norm

array([[0.632     , 0.52422907, 0.78395062, 0.3597561 , 0.13934426],
       [0.564     , 0.5154185 , 0.21604938, 0.57926829, 0.64754098],
       [0.        , 1.        , 1.        , 0.32926829, 0.09016393],
       [0.476     , 0.94713656, 0.30864198, 0.70121951, 0.8442623 ],
       [0.276     , 0.02643172, 0.33333333, 0.65243902, 0.20491803],
       [0.636     , 0.99118943, 0.97530864, 0.        , 0.        ],
       [1.        , 0.        , 0.97530864, 0.0304878 , 0.00819672],
       [0.224     , 0.18942731, 0.0308642 , 0.42073171, 0.66393443],
       [0.52      , 0.14977974, 0.        , 0.54878049, 0.3852459 ],
       [0.852     , 0.27312775, 0.60493827, 1.        , 1.        ]])

In [31]:
X_norm.max(), X_norm.min()

(1.0, 0.0)